// Auto-generated dataset from questionsv4.csv
export const pestDatasetFromCSV = [
  {
    crop: 'brinjal',
    symptoms: ["wilting"],
    pest: 'Bacterial Wilt',
    scientificName: 'To be updated',
    pesticide: 'CROP GUARD',
    alternativeName: 'CROP GUARD',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'coconut',
    symptoms: ["rotting"],
    pest: 'Unknown Pest',
    scientificName: 'To be updated',
    pesticide: 'COPPER GUARD',
    alternativeName: 'COPPER GUARD',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'potato',
    symptoms: ["wilting"],
    pest: 'Bacterial Wilt',
    scientificName: 'To be updated',
    pesticide: 'CROP GUARD',
    alternativeName: 'CROP GUARD',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'potato',
    symptoms: ["wilting"],
    pest: 'Bacterial Wilt',
    scientificName: 'To be updated',
    pesticide: 'CROP GUARD',
    alternativeName: 'CROP GUARD',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'tomato',
    symptoms: ["wilting"],
    pest: 'Bacterial Wilt',
    scientificName: 'To be updated',
    pesticide: 'CROP GUARD',
    alternativeName: 'CROP GUARD',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'tomato',
    symptoms: ["wilting"],
    pest: 'Bacterial Wilt',
    scientificName: 'To be updated',
    pesticide: 'CROP GUARD',
    alternativeName: 'CROP GUARD',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'brinjal',
    symptoms: ["wilting"],
    pest: 'Bacterial Wilt',
    scientificName: 'To be updated',
    pesticide: 'ALL CLEAR',
    alternativeName: 'ALL CLEAR',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'brinjal',
    symptoms: ["rotting"],
    pest: 'Unknown Pest',
    scientificName: 'To be updated',
    pesticide: 'CROP GUARD',
    alternativeName: 'CROP GUARD',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'maize',
    symptoms: ["rotting"],
    pest: 'Unknown Pest',
    scientificName: 'To be updated',
    pesticide: 'ALL CLEAR',
    alternativeName: 'ALL CLEAR',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'brinjal',
    symptoms: ["wilting"],
    pest: 'Bacterial Wilt',
    scientificName: 'To be updated',
    pesticide: 'ALL CLEAR',
    alternativeName: 'ALL CLEAR',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'brinjal',
    symptoms: ["rotting"],
    pest: 'Unknown Pest',
    scientificName: 'To be updated',
    pesticide: 'CROP GUARD',
    alternativeName: 'CROP GUARD',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'brinjal',
    symptoms: ["rotting"],
    pest: 'Unknown Pest',
    scientificName: 'To be updated',
    pesticide: 'CROP GUARD',
    alternativeName: 'CROP GUARD',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'brinjal',
    symptoms: ["rotting"],
    pest: 'Unknown Pest',
    scientificName: 'To be updated',
    pesticide: 'CROP GUARD',
    alternativeName: 'CROP GUARD',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'rice',
    symptoms: ["yellowing"],
    pest: 'Stem Borer',
    scientificName: 'To be updated',
    pesticide: 'SPRINT',
    alternativeName: 'SPRINT',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'brinjal',
    symptoms: ["rotting"],
    pest: 'Unknown Pest',
    scientificName: 'To be updated',
    pesticide: 'ALL CLEAR',
    alternativeName: 'ALL CLEAR',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'tomato',
    symptoms: ["wilting"],
    pest: 'Bacterial Wilt',
    scientificName: 'To be updated',
    pesticide: 'CROP GUARD',
    alternativeName: 'CROP GUARD',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'potato',
    symptoms: ["wilting"],
    pest: 'Bacterial Wilt',
    scientificName: 'To be updated',
    pesticide: 'CROP GUARD',
    alternativeName: 'CROP GUARD',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'tomato',
    symptoms: ["wilting"],
    pest: 'Bacterial Wilt',
    scientificName: 'To be updated',
    pesticide: 'CROP GUARD',
    alternativeName: 'CROP GUARD',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'tomato',
    symptoms: ["wilting"],
    pest: 'Bacterial Wilt',
    scientificName: 'To be updated',
    pesticide: 'CROP GUARD',
    alternativeName: 'CROP GUARD',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'brinjal',
    symptoms: ["wilting"],
    pest: 'Bacterial Wilt',
    scientificName: 'To be updated',
    pesticide: 'DITHANE M-45',
    alternativeName: 'DITHANE M-45',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'tomato',
    symptoms: ["wilting"],
    pest: 'Bacterial Wilt',
    scientificName: 'To be updated',
    pesticide: 'SPRINT',
    alternativeName: 'SPRINT',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: '2 per litre',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'brinjal',
    symptoms: ["wilting"],
    pest: 'Bacterial Wilt',
    scientificName: 'To be updated',
    pesticide: 'CROP GUARD',
    alternativeName: 'CROP GUARD',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: '3 per litre',
    safetyInterval: 14,
    confidence: 85
  },
  {
    crop: 'brinjal',
    symptoms: ["wilting"],
    pest: 'Bacterial Wilt',
    scientificName: 'To be updated',
    pesticide: 'CROP GUARD',
    alternativeName: 'CROP GUARD',
    dosage: '300-500 ml/acre',
    applicationMethod: 'spray',
    dosageDetails: 'As per label directions',
    safetyInterval: 14,
    confidence: 85
  },
];
